admin-shop/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::view('/', 'admin.index')->name('admin.index');

    //Category
    Route::get('category/list',[CategoryController::class, 'list'])->name('category.list');
    Route::get('category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('category/update/{id}', [CategoryController::class, 'update'])->name('category.update');
    Route::post('category/search', [CategoryController::class, 'search'])->name('category.search');
    Route::resource('category', CategoryController::class);

    //Product
    Route::get('product/list',[ProductController::class, 'list'])->name('product.list');
    Route::post('product/search', [ProductController::class, 'search'])->name('product.search');
    Route::get('product/getData/{id}', [ProductController::class ,'getDataById'])->name('product.getData');
    Route::resource('product', ProductController::class);

    //User
    Route::get('user/list',[UserController::class, 'list'])->name('user.list');
    Route::post('user/search', [UserController::class, 'search'])->name('user.search');
    Route::get('user/getData/{id}', [UserController::class, 'getDataById'])->name('user.getData');
    Route::resource('user', UserController::class);

    //Role
    Route::get('roles-list', [RoleController::class, 'list'])->name('role.list');
    Route::post('role/search', [RoleController::class, 'search'])->name('role.search');
    Route::get('role/getData/{id}', [RoleController::class, 'getDataById'])->name('role.getData');
    Route::resource('role', RoleController::class);

});

Route::get('admin/category', [CategoryController::class, 'index'])->name('category.index')
    ->middleware('can:category-list');
Route::get('admin/category/create', [CategoryController::class, 'create'])->name('category.create')
    ->middleware('can:category-add');
Route::get('admin/category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit')
    ->middleware('can:category-edit');

admin-shop/app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\HasImage;
use Illuminate\Database\Eloquent\Model;

define('IMAGE_PATH', 'img/upload/product');

class Product extends Model
{

    use HasImage;

    protected $table = "products";

    protected $fillable = [
        'name',
        'description',
        'thumbnail',
        'quantity',
        'price',
        'category_id',
        'status'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function store($data)
    {
        $file = $data->thumbnail;
        $file_name = time() . str_replace(' ', '_', $file->getClientOriginalName());
        $attributes = $data->all();
        $attributes['thumbnail'] = $file_name;
        $product = Product::create($attributes);
        $file->move('img/upload/product', $file_name);
        return $product;
    }

    public function search($data)
    {
        return $this->withName($data)->when($data, function ($query) use ($data) {
            return $query->orWhere('status', (int)$data);
        })->paginate(5);
    }

    public function scopeWithName($query, $name)
    {
        return $name
            ? $query->where('name', 'LIKE', '%' . $name . '%')
            : null;
    }
}

admin-shop/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $product;
    protected $category;

    public function __construct(Product $product, Category $category)
    {
        $this->product = $product;
        $this->category = $category;
    }

    public function index()
    {
        $categories = $this->category->all();
        return view('admin.pages.product.index', compact('categories'));
    }

    public function list(Request $request)
    {
        $data = $request['data'];
        $products = $this->product->search($data);
        return view('admin.pages.product.list', compact('products'));
    }

    public function create()
    {
        $category = $this->category->getWithPagination();
        return view('admin.pages.product.add', compact('category'));
    }

    public function store(StoreProductRequest $request)
    {
        $this->product->store($request);
        return redirect()->route('product.index')->with('message', 'Successfully Created');
    }

    public function edit($id)
    {
        $category = $this->category->getWithPagination();
        $product = $this->product->findOrFail($id);
        return response()->json(['category' => $category, 'product' => $product]);
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $data = $request->all();
        $product = $this->product->findOrFail($id);
        $fileName = $this->product->updateImage($request, $product->thumbnail);
        $data['thumbnail'] = $fileName;
        $product->update($data);
        return response()->json(['message' => "Successfully Edited"]);
    }

    public function destroy($id)
    {
//        $product = $this->product->findOrFail($id);
//        $product->destroy();
        Product::destroy($id);
        return response()->json(['message' => "Successfully deleted"]);
    }

    public function search(Request $request)
    {
        $data = $request['data'];
        $products = $this->product->search($data);
        return view('admin.pages.product.list', compact('categories', 'products'));
    }
}

admin-shop/resources/views/admin/pages/product/add.blade.php
@extends('admin.layouts.master')

@section('title')
    Add Product
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Product</h6>
        </div>
        <div class="row" style="margin: 5px">
            <div class="col-lg-12">
                <form role="form" action="{{route('product.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <fieldset class="form-group">
                        <label>Name Product</label>
                        <input class="form-control" name="name" placeholder="Enter Name Product ">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </fieldset>
                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="number" name="quantity" min="1" value="1" class="form-control">
                        @if($errors->has('quantity'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="text" name="price" placeholder="Enter Price Product" class="form-control">
                        @if($errors->has('price'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="promotional">Thumbnail</label>
                        <input type="file" name="thumbnail" class="form-control">
                        @if($errors->has('thumbnail'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" id="demo" cols="5" rows="5" class="form-control"></textarea>
                        @if($errors->has('description'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Category</label>
                        <select class="form-control cateProduct" name="category_id">
                            @foreach($category as $cate)
                                <option value="{{ $cate->id }}">{{ $cate->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Status</label>
                        <select class="form-control" name="status">
                            <option value="1">Active</option>
                            <option value="0">Deactive</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </form>
            </div>
        </div>
    </div>
@endsection

admin-shop/resources/views/admin/pages/product/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Index Product
@endsection

@section('content')
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search formSearch"
          id="formSearch">
        <div class="input-group" style="margin-top: 10px">
            <input type="text" id="txt-SearchProduct" class="form-control bg-light border-0 abc"
                   placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2 ">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="btn-SearchProduct"
                        data-url="{{route('product.search')}}">
                    <i class="fas fa-search fa-sm"></i>
                </button>
                <a href="{{route('product.create')}}">
                    <button type="button" class="btn btn-success">Add</button>
                </a>
            </div>
        </div>
    </form>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Index Product</h6>
        </div>
        <div id="listProduct" data-action="{{route('product.list')}}">
        </div>
    </div>

    <!-- Edit Modal-->
    <div class="modal fade " id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Product <span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger d-none" id="errorMsg" role="alert">
                        <ul></ul>
                    </div>
                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form id="updateProductForm" method="post"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="id" class="idProduct">
                                <fieldset class="form-group">
                                    <label>Name Product</label>
                                    <input class="form-control name" name="name" placeholder="Enter name product "
                                           id="product_name">
                                    <div class=" errorName"></div>
                                    <span class="errors error-name  text-danger"></span>
                                </fieldset>
                                <div class="form-group">
                                    <label for="quantity">Quantity</label>
                                    <input type="number" name="quantity" min="1" value="1" class="form-control quantity"
                                           id="product_quantity">
                                    <div class=" errorQuantity"></div>
                                </div>
                                <div class="form-group">
                                    <label for="price">Price</label>
                                    <input type="text" name="price" placeholder="Enter Price" class="form-control price"
                                           id="product_price">
                                    <div class=" errorPrice"></div>
                                </div>
                                <img id="target" class="img img-thumbnail imageThum" width="100" height="100"
                                     lign="center">
                                <div class="form-group">
                                    <label>Thumbnail</label>
                                    <input type="file" name="thumbnail" class="form-control image" id="src">
                                    <span class="errors error-thumbnail  text-danger"></span>
                                    <div class=" errorImage"></div>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <textarea name="description" cols="5" rows="5"
                                              class="form-control description" id="product_description"></textarea>
                                    <div class=" errorDescription"></div>
                                </div>
                                <div class="form-group">
                                    <label>Category</label>
                                    <select class="form-control cateProduct" name="category_id" id="category_id">
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control status" name="status" id="product_status">
                                        <option value="1" class="ht">Active</option>
                                        <option value="0" class="kht">Deactive</option>
                                    </select>
                                </div>
                                <button type="button" class="btn btn-success btn-update-product" value="Edit">Edit
                                </button>
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- delete Modal-->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Do you want to delete ?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success deletePro">Yes</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">No</button>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('assets/admin/js/product.js')}}"></script>
    <script src="{{asset('assets/admin/js/demo/edproduct.js')}}"></script>
@endsection

@section('style')
    <style>
        .errors {
            font-size: 1rem !important;
        }
    </style>
@endsection

admin-shop/resources/views/admin/pages/product/list.blade.php
<div class="card-body list" id="listProduct" data-action="{{route('product.list')}}">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Thumbnail</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>

            @foreach($products as $key => $value)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $value->name }}</td>
                    <td>{{ $value->description }}</td>
                    <td>
                        <img src="{{asset('img/upload/product')}}{{ '/'.$value->thumbnail }}" width="100" height="100">
                    </td>
                    <td>{{ ($value->category)->name}}</td>
                    <td>{{ $value->quantity }}</td>
                    <td>{{ $value->price }}</td>
                    <td>
                        @if( $value->status == 1 )
                            {{"Active"}}
                        @else
                            {{"Deactive"}}
                        @endif
                        </td>

                    <td>
                        <button class="btn btn-primary editProduct"
                                title="{{ "Edit ".$value->name }}"
                                data-toggle="modal" data-target="#edit"
                                type="button"
                                data-url="{{route('product.getData',$value->id)}}"
                                data-action="{{route('product.update',$value->id)}}"
                                data-id="{{ $value->id }}">
                            <i class="fas fa-edit">

                            </i>
                        </button>
                        <button class="btn btn-danger deleteProduct" data-url="{{route('product.destroy',$value->id)}}" title="{{ "Delete ".$value->name }}" data-toggle="modal" data-target="#delete" type="button" data-id="{{ $value->id }}"><i class="fas fa-trash-alt"></i></button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="-pull-right">{{ $products->links() }}</div>
    </div>
</div>