admin-shop/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::view('/', 'admin.index')->name('admin.index');

    //Category
    Route::get('category/list',[CategoryController::class, 'list'])->name('category.list');
    Route::get('category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('category/update/{id}', [CategoryController::class, 'update'])->name('category.update');
    Route::post('category/search', [CategoryController::class, 'search'])->name('category.search');
    Route::resource('category', CategoryController::class);

    //Product
    Route::get('product/list',[ProductController::class, 'list'])->name('product.list');
    Route::post('product/search', [ProductController::class, 'search'])->name('product.search');
    Route::get('product/getData/{id}', [ProductController::class ,'getDataById'])->name('product.getData');
    Route::resource('product', ProductController::class);

    //User
    Route::get('user/list',[UserController::class, 'list'])->name('user.list');
    Route::post('user/search', [UserController::class, 'search'])->name('user.search');
    Route::get('user/getData/{id}', [UserController::class, 'getDataById'])->name('user.getData');
    Route::resource('user', UserController::class);

    //Role
    Route::get('roles-list', [RoleController::class, 'list'])->name('role.list');
    Route::post('role/search', [RoleController::class, 'search'])->name('role.search');
    Route::get('role/getData/{id}', [RoleController::class, 'getDataById'])->name('role.getData');
    Route::resource('role', RoleController::class);

});

Route::get('admin/category', [CategoryController::class, 'index'])->name('category.index')
    ->middleware('can:category-list');
Route::get('admin/category/create', [CategoryController::class, 'create'])->name('category.create')
    ->middleware('can:category-add');
Route::get('admin/category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit')
    ->middleware('can:category-edit');

admin-shop/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table = 'roles';
    protected $guarded = [];


    protected $fillable = [
        'name',
        'description',
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function getWithPaginate()
    {
        return Role::paginate(5);
    }

    public function search($data)
    {
        return Role::withName($data)->when($data, function ($query) use ($data) {
            return $query;
        })->paginate(5);
    }

    public function scopeWithName($query, $name)
    {
        return $name
            ? $query->where('name', 'LIKE', '%' . $name . '%')
            : null;
    }

}

admin-shop/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public $user;
    public $role;
    public $permission;

    public function __construct(Role $role, User $user, Permission $permission)
    {
        $this->user = $user;
        $this->permission = $permission;
        $this->role = $role;
    }

    public function index()
    {
        $roles = $this->role->getWithPaginate();
        return view('admin.pages.role.index', compact('roles'));
    }

    public function list(Request $request)
    {
        $data = $request['data'];
        $roles = $this->role->search($data);
        return view('admin.pages.role.list', compact('roles'));
    }

    public function create()
    {
        $permissionsParent = $this->permission->where('parent_id', 0)->get();
        $roles = $this->role->all();
        return view('admin.pages.role.add', compact('roles', 'permissionsParent'));
    }

    public function store(StoreRoleRequest $request)
    {
        $role = $this->role->create([
            'name' => $request->name,
            'description' => $request->description,
        ]);
        $role->permissions()->sync($request->permission_id);
        return redirect()->route('role.index');
    }

    public function update(StoreRoleRequest $request, $id)
    {
        $role = $this->role->findOrFail($id);
        $data = $request->all();
        ($role->update($data));
        $role->permissions()->sync($request->permission_id);
        return redirect()->route('role.index');
    }

    public function destroy($id)
    {
        $role = $this->role->findOrFail($id);
        $role->destroy();
        return response()->json(['message' => 'Successfully Deleted']);
    }

    public function search(Request $request)
    {
        $data = $request['data'];
        $roles = $this->role->search($data);
        return view('admin.pages.role.list', compact('roles'));
    }

    public function edit($id)
    {
        $permissionsParent = $this->permission->where('parent_id', 0)->get();
        $role = $this->role->findOrFail($id);
        $permissionsChecked = $role->permissions;
        return view('admin.pages.role.edit', compact('role', 'permissionsParent', 'permissionsChecked'));
    }
}

admin-shop/resources/views/admin/pages/role/add.blade.php
@extends('admin.layouts.master')

@section('title')
    Add Role
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Role</h6>
        </div>
        <div class="row" style="margin: 5px">
            <form role="form" action="{{route('role.store')}}" method="post">
                <div class="col-lg-12">
                    @csrf
                    <fieldset class="form-group">
                        <label>Role name</label>
                        <input class="form-control" name="name" placeholder="Enter role name ">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </fieldset>
                    <div class="form-group">
                        <label>Description</label>
                        <input type="text" name="description" placeholder="Enter description role" class="form-control">
                        @if($errors->has('description'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            @foreach($permissionsParent as $permissionsParentItem)
                                <div class="card border-primary mb-3 col-md-12">
                                    <div class="card-header">
                                        <label>
                                            <input type="checkbox" value="" class="checkbox_wrapper">
                                        </label>
                                        Module {{$permissionsParentItem->name}}
                                    </div>
                                    <div class="row">
                                        @foreach($permissionsParentItem->permissionsChildrent as $permissionsChildrentItem)
                                            <div class="card-body text-primary col-md-3">
                                                <h5 class="card-title">
                                                    <label>
                                                        <input type="checkbox" name="permission_id[]"
                                                               class="checkbox_childrent"
                                                               value="{{$permissionsChildrentItem->id}}">
                                                    </label>
                                                    {{$permissionsChildrentItem->name}}
                                                </h5>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $('.checkbox_wrapper').on('click', function () {
            $(this).parents('.card').find('.checkbox_childrent').prop('checked',$(this).prop('checked'));
        });
    </script>
@endsection

admin-shop/resources/views/admin/pages/role/edit.blade.php
@extends('admin.layouts.master')

@section('title')
    Edit Role
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Role</h6>
        </div>
        <div class="row" style="margin: 5px">
            <div class="col-lg-12">
                <form role="form" action="{{route('role.update',$role->id)}}" method="POST">
                    @method('PUT')
                    @csrf
                    <fieldset class="form-group">
                        <label>Role name</label>
                        <input class="form-control" name="name" placeholder="Enter role name" value="{{$role->name}}">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </fieldset>
                    <div class="form-group">
                        <label>Description</label>
                        <input type="text" name="description" placeholder="Enter description role" class="form-control" value="{{$role->description}}">
                        @if($errors->has('description'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            @foreach($permissionsParent as $permissionsParentItem)
                                <div class="card border-primary mb-3 col-md-12">
                                    <div class="card-header">
                                        <label>
                                            <input type="checkbox" value="" class="checkbox_wrapper">
                                        </label>
                                        Module {{$permissionsParentItem->name}}
                                    </div>
                                    <div class="row">
                                        @foreach($permissionsParentItem->permissionsChildrent as $permissionsChildrenItem)
                                            <div class="card-body text-primary col-md-3">
                                                <h5 class="card-title">
                                                    <label>
                                                        <input type="checkbox" name="permission_id[]"
                                                               {{$permissionsChecked->contains('id',$permissionsChildrenItem->id) ? 'checked' : '' }}
                                                               class="checkbox_childrent"
                                                               value="{{$permissionsChildrenItem->id}}">
                                                    </label>
                                                    {{$permissionsChildrenItem->name}}
                                                </h5>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

admin-shop/resources/views/admin/pages/role/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Index Role
@endsection

@section('content')
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search formSearch" id="formSearch" >
        <div class="input-group" style="margin-top: 10px">
            <input type="text" id="txt-SearchRole" class="form-control bg-light border-0 abc" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2 ">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="btn-SearchRole" data-url="{{route('role.search')}}">
                    <i class="fas fa-search fa-sm"></i>
                </button>
                <a href="{{route('role.create')}}"><button type="button" class="btn btn-success">ADD</button></a>
            </div>
        </div>
    </form>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Role</h6>
        </div>
        <div id="listRole" data-action="{{route('role.list')}}">
        </div>
    </div>

    <!-- Edit Modal-->
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa Role <span class="title"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="row" style="margin: 5px">
                        <div class="col-lg-12">
                            <form role="form" id="role_data">
                                <fieldset class="form-group">
                                    <label>Vai trò</label>
                                    <input class="form-control name" name="name" placeholder="Nhập tên vai trò " id="role_name">
                                    <span class="error" style="color: red; font-size: 1rem"></span>
                                    <span class="errors error-name  text-danger"></span>
                                </fieldset>

                                <fieldset class="form-group">
                                    <label>Mô tả vai trò</label>
                                    <input class="form-control name" name="description" placeholder="Nhập tên mô tả vai trò " id="role_description">
                                    <span class="error" style="color: red; font-size: 1rem"></span>
                                    <span class="errors error-name  text-danger"></span>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-success updateRole">Save</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <!-- delete Modal-->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Do you want to delete?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success deleteWithRole">Yes</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">No</button>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{asset('assets/admin/js/role.js')}}"></script>
@endsection

admin-shop/resources/views/admin/pages/role/list.blade.php
<div class="card-body list-multi" id="listRole" data-action="{{route('role.list')}}">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>Role name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody id="list-role">
            @foreach($roles as $key => $value)
                <tr>
                    <td>{{ $key+1 }}</td>
                    <td>{{ $value->name }}</td>
                    <td>{{ $value->description }}</td>
                    <td>
                        <a href="{{route('role.edit',$value->id)}}"><button class="btn btn-primary editRole" title="{{ "Edit ".$value->name }}"  data-target="#edit" type="button" data-id="{{ $value->id }}" data-url="{{route('role.getData',$value->id)}}" data-action="{{route('role.update',$value->id)}}"><i class="fas fa-edit"></i></button></a>
                        <button class="btn btn-danger deleteRole" data-url="{{route('role.destroy',$value->id)}}" title="{{ "Delete ".$value->name }}"  data-toggle="modal" data-target="#delete" type="button" data-id="{{ $value->id }}"><i class="fas fa-trash-alt"></i></button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>