admin-shop/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::view('/', 'admin.index')->name('admin.index');

    //Category
    Route::get('category/list',[CategoryController::class, 'list'])->name('category.list');
    Route::get('category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('category/update/{id}', [CategoryController::class, 'update'])->name('category.update');
    Route::post('category/search', [CategoryController::class, 'search'])->name('category.search');
    Route::resource('category', CategoryController::class);

    //Product
    Route::get('product/list',[ProductController::class, 'list'])->name('product.list');
    Route::post('product/search', [ProductController::class, 'search'])->name('product.search');
    Route::get('product/getData/{id}', [ProductController::class ,'getDataById'])->name('product.getData');
    Route::resource('product', ProductController::class);

    //User
    Route::get('user/list',[UserController::class, 'list'])->name('user.list');
    Route::post('user/search', [UserController::class, 'search'])->name('user.search');
    Route::get('user/getData/{id}', [UserController::class, 'getDataById'])->name('user.getData');
    Route::resource('user', UserController::class);

    //Role
    Route::get('roles-list', [RoleController::class, 'list'])->name('role.list');
    Route::post('role/search', [RoleController::class, 'search'])->name('role.search');
    Route::get('role/getData/{id}', [RoleController::class, 'getDataById'])->name('role.getData');
    Route::resource('role', RoleController::class);

});

Route::get('admin/category', [CategoryController::class, 'index'])->name('category.index')
    ->middleware('can:category-list');
Route::get('admin/category/create', [CategoryController::class, 'create'])->name('category.create')
    ->middleware('can:category-add');
Route::get('admin/category/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit')
    ->middleware('can:category-edit');

admin-shop/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'ruler',
        'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function getWithPaginate()
    {
        return $this->paginate(5);
    }

    public function hasRoles($roles = []): bool
    {
        return $this->roles()->whereIn('name', $roles)->count() > 0;
    }

    public function search($data)
    {
        return $this->withName($data)->when($data, function ($query) use ($data) {
            return $query->orWhere('status', (int)$data);
        })->paginate(5);
    }

    public function checkPermissionAccess($permissionCheck)
    {
        $roles = auth()->user()->roles;
        foreach ($roles as $role) {
            $permissions = $role->permissions;
            if ($permissions->contains('key_code', $permissionCheck)) {
                return true;
            }
        }
        return false;
    }

    public function scopeWithName($query, $name)
    {
        return $name
            ? $query->where('name', 'LIKE', '%' . $name . '%')
            : null;
    }
}

admin-shop/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public $user;
    public $role;

    public function __construct(User $user, Role $role)
    {
        $this->user = $user;
        $this->role = $role;
    }

    public function index()
    {
        $roles = $this->role->all();
        $users = $this->user->getWithPaginate();
        return view('admin.pages.user.index', compact('users', 'roles'));
    }

    public function list(Request $request)
    {
        $data = $request['data'];
        $users = $this->user->search($data);
        return view('admin.pages.user.list', compact('users'));
    }

    public function create()
    {
        $roles = $this->role->all();
        return view('admin.pages.user.add', compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        $user = $this->user->create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->newPassword),
        ]);
        $user->roles()->sync($request->role_id);
        return redirect()->route('user.index');
    }

    public function edit($id)
    {
        $user = $this->user->with('roles')->findOrFail($id);
        $roles = $this->role->all();
        return view('admin.pages.user.edit', compact('user', 'roles'));
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $user = $this->user->findOrFail($id);
        $user->update($request->all());
        $user->roles()->sync($request->role_id);
        return response()->json(['message' => 'Successfully Edited']);
    }

    public function destroy($id)
    {
        $user = $this->user->findOrFail($id);
        $user->destroy();
        return response()->json(['message' => 'Successfully Deleted']);
    }

    public function search(Request $request)
    {
        $data = $request['data'];
        $users = $this->user->search($data);
        return view('admin.pages.user.list', compact('users'));
    }
}

admin-shop/resources/views/admin/pages/user/add.blade.php
@extends('admin.layouts.master')

@section('title')
    Create user
@endsection

@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">User</h6>
        </div>
        <div class="row" style="margin: 5px">
            <div class="col-lg-12">

                <form role="form" action="{{route('user.store')}}" method="post">
                    @csrf
                    <fieldset class="form-group">
                        <label>Name</label>
                        <input class="form-control" name="name" placeholder="Enter name User ">
                        @if($errors->has('name'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </fieldset>
                    <div class="form-group" >
                        <label >Email</label>
                        <input type="text" name="email"  placeholder="Enter email" class="form-control">
                        @if($errors->has('email'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group" >
                        <label>Password</label>
                        <input type="text" name="password"  placeholder="Enter password" class="form-control">
                        @if($errors->has('password'))
                            <div class="alert alert-danger">{{$errors->all()[0]}}</div>
                        @endif
                    </div>
                    <div class="form-group" >
                        <label>Role</label>
                        <select name="role_id[]" class="browser-default custom-select" multiple>
                            @foreach($roles as $role)
                                <option value="{{$role->id}}">{{$role->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </form>
            </div>
        </div>
    </div>
@endsection

admin-shop/resources/views/admin/pages/user/edit.blade.php
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Edit User <span class="title"></span></h5>
    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body">
    <div class="alert alert-danger d-none" id="errorMsg" role="alert">
        <ul></ul>
    </div>
    <div class="row" style="margin: 5px">
        <div class="col-lg-12">
            <form role="form" id="user_data" data-action="{{ route('user.update', $user->id) }}" method="post">
                @method('PUT')
                <fieldset class="form-group">
                    <label>Name</label>
                    <input class="form-control " name="name" value="{{ $user->name }}" placeholder="Enter name User "
                           id="user_name">
                    <div class=" errorName"></div>
                    <span class="errors error-name  text-danger"></span>
                </fieldset>

                <fieldset class="form-group">
                    <label>Email</label>
                    <input class="form-control" name="email" value="{{ $user->email }}" placeholder="Enter name Email "
                           id="user_email">
                    <div class=" errorName"></div>
                    <span class="errors error-name text-danger"></span>
                </fieldset>
                <fieldset class="form-group">
                    <label>Role</label>
                    <select class="select2 form-control" multiple="multiple" name="role_id[]"
                            data-placeholder="Select a role">
                        @foreach($roles as $role)
                            <option
                                {{ $user->roles->contains('id', $role->id) ? 'selected' : '' }}
                                value="{{ $role->id }}">{{ $role->name }}
                            </option>
                        @endforeach
                    </select>
                </fieldset>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success updateUser">Save</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

admin-shop/resources/views/admin/pages/user/index.blade.php
@extends('admin.layouts.master')

@section('title')
    Index User
@endsection

@section('content')
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search formSearch" id="formSearch" >
        <div class="input-group" style="margin-top: 10px">
            <input type="text" id="txt-SearchUser" class="form-control bg-light border-0 abc" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2 ">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="btn-SearchUser" data-url="{{route('user.search')}}">
                    <i class="fas fa-search fa-sm"></i>
                </button>
                <a href="{{route('user.create')}}"><button type="button" class="btn btn-success">ADD</button></a>
            </div>
        </div>
    </form>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">User</h6>
        </div>
        <div id="listUser" data-action="{{route('user.list')}}">
        </div>
    </div>

    <!-- Edit Modal-->
    <div class="modal fade " id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>

    <!-- delete Modal-->
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Do you want to delete?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" style="margin-left: 183px;">
                    <button type="button" class="btn btn-success deleteWithUser">yes</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">no</button>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('assets/admin/js/user.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
@endsection

admin-shop/resources/views/admin/pages/user/list.blade.php
<div class="card-body list-multi" id="listUser" data-action="{{route('user.list')}}">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody id="list-user">
            @foreach($users as $key => $value)
                <tr>
                    <td>{{ $key+1 }}</td>
                    <td>{{ $value->name }}</td>
                    <td>{{ $value->email }}</td>
                    <td>
                        <button class="btn btn-primary editUser" title="{{ "Sửa ".$value->name }}" data-toggle="modal" data-target="#edit" type="button" data-id="{{ $value->id }}" data-url="{{route('user.edit',$value->id)}}" data-action="{{route('user.update',$value->id)}}"><i class="fas fa-edit"></i></button>
                        <button class="btn btn-danger deleteUser" data-url="{{route('user.destroy',$value->id)}}" title="{{ "Xóa ".$value->name }}" data-toggle="modal" data-target="#delete" type="button" data-id="{{ $value->id }}"><i class="fas fa-trash-alt"></i></button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{--        <div class="pull-right">{{ $category->links() }}</div>--}}
    </div>
</div>